service: serverless1
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  memorySize: 128
  timeout: 15
  environment:
    DEPLOY_ENV: ${opt:stage, 'dev'}
functions:
  chat:
    handler: handler.chat
    events:
      - http:
         path: sms
         method: post
