on:
  push:
    branches:
      - demo
name: Deploy app to AWS and register API endpoint with SMS provider
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install 
    - run: npx serverless deploy --stage $ENVIRONMENT -v
    - run: npx -p twilio-cli twilio phone-numbers:update $MOBILE_NUMBER --sms-url=$(npx serverless info --stage $ENVIRONMENT | grep -ow https.*)
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID_DEV }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN_DEV }}
      MOBILE_NUMBER: ${{ secrets.MOBILE_NUMBER_DEV }}
      ENVIRONMENT: dev
